# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blank.gif', upload_to='assets/avatar'),
        ),
    ]
