# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/blank.gif', upload_to='avatar'),
        ),
    ]
