# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpermission',
            name='access_level',
            field=models.CharField(default='read', max_length=10),
        ),
    ]
