# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpermission',
            options={'ordering': ('id',)},
        ),
    ]
