# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170315_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('position',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='board',
            new_name='cardlist',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
