# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
    ]
