# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170315_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
